### ISSUE TITLE
How do i send to all client?

### ISSUE THREAD

**Issue by Droog159** [evolutionleo/GM-Online-Framework#1]
Thank you very much for your code.
How do i send to all client?

**Comment by Droog159** [comment]
Sorry, I saw it, thank you again for sharing，nice man，i like you.

**Comment by Droog159** [comment]
2.3 After the update, we can finally send packages with json

**Comment by Ookami-Git** [comment]
Hello,
i have the same issue.
All my client is connected to the server but their reveive only the package what they send.

How did you fix it ?
Thx.

EDIT : I use version 2.1

**Comment by evolutionleo** [comment]
@Ookami-Git call c.broadcastAll()

**Comment by Ookami-Git** [comment]
Hi,
Thank you for the quick reply !

Where i call this ? 
in handlepacket.js ?

For example if i want send this everywhere : 

        case 'hello':
            console.log("Hello from client: "+data.kappa);
            c.sendHello();
            break;

Where i need to add c.boradcastAll() ?


EDIT : 
Ok i think i found,

for this example (just for test) the code for broadcast is 

        case 'hello':
            console.log("Hello from client: "+data.kappa);
            c.broadcastAll({cmd: 'hello', str: 'Hello, client!'});
            c.broadcastAll({cmd: 'hello2', str: 'Hello again, client!'});
            //c.sendHello();
            break;

I try on my custom commands and that work well.
Thanks !

**Comment by evolutionleo** [comment]
You're welcome :p
