### ISSUE TITLE
Spelling Issue

### ISSUE THREAD

**Issue by 123HD123** [evolutionleo/GM-Online-Framework#15]
https://github.com/evolutionleo/Warp/blob/afe69a72a7bd0c82885501863e3c41644b722e1e/TypescriptServer/tsconfig.json#L25
Not sure how much this matters but should be "node_modules/*".

**Comment by evolutionleo** [comment]
wow no idea how I haven't noticed this, thanks. fixed in the latest commit
it shouldn't be that relevant if the thing works with the typo i guess haha
still, thanks for noticing though!
