### ISSUE TITLE
Spelling Issue #2

### ISSUE THREAD

**Issue by 123HD123** [evolutionleo/GM-Online-Framework#16]
https://github.com/evolutionleo/Warp/blob/7d4d526a2c40b3a770f0afc68e4213c048628722/TypescriptServer/src/internal/util/entity_functions.ts#L3
https://github.com/evolutionleo/Warp/blob/7d4d526a2c40b3a770f0afc68e4213c048628722/JavascriptServer/internal/util/entity_functions.js#L2

Found another one, should be "entityType".

Edit:
https://github.com/evolutionleo/Warp/blob/7d4d526a2c40b3a770f0afc68e4213c048628722/TypescriptServer/src/internal/util/load_room.ts#L14
https://github.com/evolutionleo/Warp/blob/7d4d526a2c40b3a770f0afc68e4213c048628722/JavascriptServer/internal/util/load_room.js#L6

Should be "commas".

**Comment by evolutionleo** [comment]
thank you, fixed!
