### ISSUE TITLE
Uncaught TypeError: crypto.randomInt is not a function

### ISSUE THREAD

**Issue by AnachroSoft** [evolutionleo/GM-Online-Framework#4]
Debugger attached.
Waiting for the debugger to disconnect...
c:\-redacted-\Server\internal\lobbyFunctions.js:9
        var lobbyid = crypto.randomInt(100000, 999999).toString();
                             ^

TypeError: crypto.randomInt is not a function
    at module.exports.createLobby (c:\-redacted\Server\internal\lobbyFunctions.js:9:30)
    at c:\-redacted-\Server\internal\initializers\03_lobbies.js:5:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (c:\-redacted-\Server\internal\initializers\03_lobbies.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at c:\-redacted-\Server\server.js:15:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (c:\-redacted-\Server\server.js:14:12)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
Process exited with code 1

**Comment by evolutionleo** [comment]
Sorry for late response. Have you ran the "npm install" command?

**Comment by AnachroSoft** [comment]
No worries! I did and it completed successfully.

**Comment by AnachroSoft** [comment]
> 
> 
> Sorry for late response. Have you ran the "npm install" command?

No worries. I did run that and it had completed successfully. I can try running it again.

:Edit:
I ran it again. "removed 1 package and audited 42 packages in 1.548s found 0 vulnerabilities" Tried to run the server again and still getting this error.

**Comment by evolutionleo** [comment]
Seems like you're running it through the debugger. In theory this shouldn't be a problem, but try running it via "node ." as shown in the README

**Comment by AnachroSoft** [comment]
The README doesn't actually say how to run the server. At least not in the EmptyServer.zip. However, I did try to run "node server.js" both through Windows command prompt and through VSC's command line. Both give the same error as running through the debugger. =(

**Comment by evolutionleo** [comment]
Oh, I think I know what's the issue. Update your NodeJS, some of the older versions didn't have the function "randomInt" in the internal module "crypto"

**Comment by evolutionleo** [comment]
btw the README does have the instructions under the "Running" section (https://github.com/evolutionleo/GM-Online-Framework#runnning)
It can be easy to miss accidentally though

Oh, I meant the repo's README

**Comment by evolutionleo** [comment]
Did that fix it?

**Comment by AnachroSoft** [comment]
> 
> 
> Oh, I think I know what's the issue. Update your NodeJS, some of the older versions didn't have the function "randomInt" in the internal module "crypto"
> Did that fix it?

Sorry about that! I hadn't had a chance, yet. I'm going to try later today and get back with you ASAP.

:Edit:
Yep, that was it! I already had NodeJS installed and did try to update it before running initially, but I realized I was installing the "tool" and not NodeJS itself. That's my bad. Thank you for your help!

**Comment by evolutionleo** [comment]
You're welcome! Glad it helped.

You can join my Discord server if you have any other questions on the framework (even minor ones): https://discord.gg/WRsgumM2T6
