### ISSUE TITLE
Broadcast functions do not exclude current client

### ISSUE THREAD

**Issue by SnoutUp** [evolutionleo/GM-Online-Framework#9]
First of all, thank you for creating this framework! Buffers are just not friends of mine...

However it looks like "notme" flag in broadcastList function doesn't work as intended as "this" is always undefined in the context of the comparison function. 

Easy fix:
```
    broadcastList(clients, pack, notme = true) {
        let me = this;
        clients.forEach(function (client) {
            if (client === me && notme) {
                // skip me
            } else {
                client.write(pack);
            }
        });
    }
```

Cheers!

**Comment by evolutionleo** [comment]
Hmm, this is really weird because I totally remember fixing this before, using a solution that is very similar to this one
I might have forgotten to change it for the TypeScript server and so it got reintroduced idk
Thank you for noticing!

**Comment by evolutionleo** [comment]
Pushed an update to fix this bug that got reintroduced. Thanks again for noticing!
